name: Continuous Deployment For Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    name: Check Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check for Merge Conflicts
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "🚨 Konflik terdeteksi! Perbaiki sebelum merge."
            exit 1
          fi
          echo "✅ Tidak ada konflik. Lanjutkan."
          
      - name: Detect Merge Conflict Markers
        run: |
          if grep -rnI "<<<<<<< main" .; then
            echo "🚨 Terdeteksi konflik di kode, tolong selesaikan!"
            exit 1
          else
            echo "✅ Tidak ada konflik yang terdeteksi."
          fi
          
  deployment:
    name: Deploy to Server
    needs: verification
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: |
          echo "✅ Success"
