name: Continuous Deployment For Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    name: Check Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ambil semua riwayat untuk memastikan deteksi akurat

      - name: Check for Merge Conflicts
        if: github.event_name == 'pull_request'
        run: |
          # Ambil branch main untuk perbandingan
          git fetch origin main
          
          # Cek apakah ada konflik terhadap main
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "🚨 Konflik terdeteksi! Perbaiki sebelum merge."
            exit 1
          fi
          echo "✅ Tidak ada konflik. Lanjutkan."
          
      - name: Detect Merge Conflict Markers
        run: |
          # Temukan commit dasar sebelum merge
          BASE_SHA=$(git merge-base origin/main HEAD)

          # Ambil file yang diubah setelah commit lokal dan pull
          CHANGED_FILES=$(git diff --name-only $BASE_SHA HEAD)

          echo "🔍 File yang diubah:"
          echo "$CHANGED_FILES"

          # Filter hanya file php, js, html dan abaikan direktori tertentu
          FILES_TO_CHECK=$(echo "$CHANGED_FILES" | grep -E '\.(php|js|html)$' | grep -Ev '^(vendor|node_modules|storage)/' || true)

          if [ -n "$FILES_TO_CHECK" ]; then
            echo "📂 File yang diperiksa:"
            echo "$FILES_TO_CHECK"

            # Deteksi marker konflik di file
            echo "$FILES_TO_CHECK" | xargs grep -Hn "<<<<<<<" && {
              echo "🚨 Terdeteksi konflik! Tolong selesaikan sebelum merge."
              exit 1
            } || echo "✅ Tidak ada konflik yang ditemukan."
          else
            echo "✅ Tidak ada file PHP, JS, atau HTML yang diubah."
          fi
          
  deployment:
    name: Deploy to Server
    needs: verification
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: |
          echo "🚀 Deploying to production..."
          # Tambahkan perintah SSH atau deployment Anda di sini
          echo "✅ Success"
