name: Continuous Deployment For Production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  verification:
    name: Check Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Detect Merge Conflict Markers
        run: |
          FILES_TO_CHECK=$(find . -type f \( -name "*.php" -o -name "*.js" -o -name "*.html" \) \
                          ! -path "./vendor/*" ! -path "./node_modules/*" ! -path "./storage/*")

          echo "📂 File yang terdapat konflik:"

          if echo "$FILES_TO_CHECK" | xargs grep -Hn "<<<<<<<" ; then
            echo "🚨 Terdeteksi konflik! Tolong selesaikan sebelum merge."
            exit 1
          else
            echo "✅ Tidak ada konflik yang ditemukan."
          fi

  deployment:
    name: Deploy to Server
    needs: verification
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Production Server
        run: |
          echo "🚀 Deploying to production..."
          echo "✅ Success"
